services:
  - docker
language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      arch: s390x
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: amd64
script:
  - echo "CPU Architecture is " $TRAVIS_CPU_ARCH
  - echo "commit is " $TRAVIS_COMMIT
  - df -h
  - make
after_success:
  - ./a.out
