services:
  - docker
language: cpp
os: 
  - linux
  - osx
dist: bionic
arch:
  - s390x
  - ppc64le
  - amd64
osx_image:
  - xcode12
  - xcode11.6
script:
  - echo "CPU Architecture is " $TRAVIS_CPU_ARCH
  - echo "commit is " $TRAVIS_COMMIT
  - df -h
  - make
after_success:
  - ./a.out
