services:
  - docker
language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      arch: s390x
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: amd64
script:
  - make
after_success:
  - ./a.out
